language: java
jdk:
  - oraclejdk8

env:
  - SPRING_PROFILES_ACTIVE=test,travis

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database zebra_test;' -U postgres

script:
  - ./gradlew cobertura coveralls