language: java
jdk:
  - oraclejdk8

env:
  - SPRING_PROFILES_ACTIVE=test,travis

services:
  - postgresql

before_script:
  - psql -c 'create database zebra_test;' -U postgres

addons:
  postgresql: "9.6"

after_success:
  - gradle jacocoTestReport coveralls