version: '2.1'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  monitoring:
    image: kamon/grafana_graphite
    ports:
      - "80:80"
      - "8125:8125"
      - "8126:8126"
      - "8000:8000"
