spring:
  datasource:
    url: jdbc:postgresql://<IP_ADDRESS>:<PORT>/DB_NAME
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
flyway:
  locations: classpath:/db/migrations,classpath:/db/dev/